
# This dockerfile builds is assumed to be built by an amd64 machine FOR an amd64 machine

# Use an official Ubuntu base image
FROM ubuntu:24.04

# Prevent interactive prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Update package list and install dependencies
RUN apt-get update && apt-get install -y \
    git \
    tree \
    build-essential \
    cmake \
    python3 \
    ninja-build \
    ccache \
    clang-format \
    clang-tidy \
    cppcheck \
    debhelper-compat \
    qt6-base-private-dev \
    qt6-base-dev \
    qtkeychain-qt6-dev \
    libqt6sql6-sqlite \
    libprotobuf-dev \
    protobuf-compiler \
    libssl-dev \
    libzstd-dev \
    xvfb \
    xdotool \
    x11-utils \
    imagemagick \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /workspace

# Default command
CMD [ "bash" ]
