name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    defaults:
      run:
        shell: bash

    container:
      image: ghcr.io/${{ vars.USERNAME }}/l2trader-builder:noble
      credentials:
        username: ${{ vars.USERNAME }}
        password: ${{secrets.TOKEN_GHCR}}

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{github.head_ref}}

      - name: clang-format
        uses: ./.github/actions/clang-format

      - name: Set up ccache
        run: |
          export CCACHE_DIR=$HOME/.cache/ccache
          echo "CCACHE_DIR=$HOME/.cache/ccache" >> $GITHUB_ENV
          ccache --version
          mkdir -p $CCACHE_DIR
          ccache --set-config=max_size=500M
          ccache --set-config=compression=true
          ccache --set-config=compression_level=6
          ccache --zero-stats

      - name: Cache ccache directory
        uses: actions/cache@v4
        with:
          path: ~/.cache/ccache
          key: ccache-debian-noble-X86-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ccache-debian-noble-X86-${{ github.ref }}
            ccache-debian-noble-X86-refs/heads/main

      - name: Configure GUI version with CMake
        run: |
          cmake --version
          mkdir -p build/GUI
          cmake -S . -B build/GUI -DCMAKE_BUILD_TYPE=Debug -DENABLE_GUI=ON -DBUILD_TESTS=OFF -DENABLE_UBSAN=OFF -DENABLE_ASAN=OFF

      - name: Configure TUI with CMake
        run: |
          cmake --version
          mkdir -p build/TUI
          cmake -S . -B build/TUI -DCMAKE_BUILD_TYPE=Debug -DENABLE_GUI=OFF -DBUILD_TESTS=OFF -DENABLE_UBSAN=OFF -DENABLE_ASAN=OFF

      - name: Build TUI targets
        run: cmake --build build/TUI -j$(nproc)

      - name: Build GUI targets
        run: cmake --build build/GUI -j$(nproc)