name: Container Build And Upload
description: |
  Builds and uploads to GHCR (GitHub Container Registry) the container used to build the app.
  This workflow will assumes the build architecture is amd64 (x86_64) since the github's 'ubuntu-latest' runs-on tag
  is used. Dockerfile in this repo's docker/ folder will be built for amd64 and cross-compiled
  for arm64.

on:
  schedule:
    # Runs at 00:00 UTC every Monday
    - cron: '0 0 * * 1'

  pull_request:
    branches:
      - main
      - development

  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:

  # Check if this PR changes files in the docker/ folder. If not, there is no point in building and pushing a new image.
  check-if-build-needed:
    runs-on: ubuntu-latest
    outputs:
      build-needed: ${{ steps.set-output.outputs.build-needed }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{github.head_ref}}
          fetch-depth: 0

      - name: Check if build is needed
        id: set-output
        run: |
          echo "build-needed=false" >> $GITHUB_OUTPUT
          
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            CHANGED_FILES=$(git diff --name-only origin/main...HEAD)
            echo "Changed files: $CHANGED_FILES"
            if [[ $CHANGED_FILES == *".github/docker/"* ]]; then
              echo "Build IS needed as .github/docker/ folder changed."
              echo "build-needed=true" >> $GITHUB_OUTPUT
            else
              echo "Build is NOT needed as .github/docker/ folder did not change."
              echo "build-needed=false" >> $GITHUB_OUTPUT
            fi

          elif [[ "${{ github.event_name }}" == "push" ]]; then
            CHANGED_FILES=$(git diff --name-only ${{ github.event.before }}..${{ github.event.after }})
            echo "Changed files: $CHANGED_FILES"
            if [[ $CHANGED_FILES == *".github/docker/"* ]]; then
              echo "Build IS needed as .github/docker/ folder changed."
              echo "build-needed=true" >> $GITHUB_OUTPUT
            else
              echo "Build is NOT needed as .github/docker/ folder did not change."
              echo "build-needed=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "Build is needed for schedule or workflow_dispatch."
            echo "build-needed=true" >> $GITHUB_OUTPUT
          fi

  # Build the amd64 natively on ubuntu-latest which is an x86_64 host
  build-image-amd64-noble:
    needs: check-if-build-needed
    if: needs.check-if-build-needed.outputs.build-needed == 'true'
    runs-on: ubuntu-24.04
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: build image
        run: |
          docker build -f .github/docker/Dockerfile.amd64.noble -t ghcr.io/${{ vars.USERNAME }}/l2trader-builder:noble .

      # Don't push to GHCR if build was triggered by a PR
      - name: Push to GHCR
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          echo ${{ secrets.TOKEN_GHCR }} | docker login ghcr.io -u ${{ vars.USERNAME }} --password-stdin
          docker push ghcr.io/${{ vars.USERNAME }}/l2trader-builder:noble

  # Build the RPI cross-compilation container on ubuntu-latest (amd64)
  build-image-rpi-bookworm:
    needs: check-if-build-needed
    if: needs.check-if-build-needed.outputs.build-needed == 'true'
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build image
        run: |
          docker build -f .github/docker/Dockerfile.rpi.bookworm -t ghcr.io/${{ vars.USERNAME }}/l2trader-builder:rpi-bookworm .

      # Don't push to GHCR if build was triggered by a PR
      - name: Push to GHCR
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          echo ${{ secrets.TOKEN_GHCR }} | docker login ghcr.io -u ${{ vars.USERNAME }} --password-stdin
          docker push ghcr.io/${{ vars.USERNAME }}/l2trader-builder:rpi-bookworm
